import assert from 'assert';
import { LocalStorageDreamRepository } from '../services/storage/LocalStorageDreamRepository';
import { DreamPatternEngine } from '../services/patterns/DreamPatternEngine';
import { StorageService } from '../services/storageService';
import type { SavedDreamRecord } from '../domain/journal/SavedDreamRecord';
import type { DreamAnalysisResult } from '../types/dream';

/**
 * STEP 6: DREAM JOURNAL & RECURRING PATTERN EXPLORER TEST SUITE
 * 
 * Verifies all 21 test criteria:
 * 1. Save dream
 * 2. Retrieve dream
 * 3. Update dream
 * 4. Delete dream
 * 5. Search dream
 * 6. Filter dream
 * 7. Duplicate prevention
 * 8. Private default
 * 9. Anonymous sharing flag
 * 10. Pattern frequency calculation
 * 11. Motif recurrence
 * 12. Emotion recurrence
 * 13. Emotional sequence
 * 14. No pattern from single occurrence
 * 15. Pattern references correct dream IDs
 * 16. Private dreams excluded from shared queries
 * 17. No psychological diagnosis generated by pattern engine
 * 18. Artwork reference preserved
 * 19. Analysis version preserved
 * 20. Empty journal behavior
 * 21. Empty pattern behavior
 */

// In-memory mock localStorage for Node testing environment
class MockLocalStorage {
  private store: Record<string, string> = {};

  getItem(key: string): string | null {
    return this.store[key] || null;
  }
  setItem(key: string, value: string): void {
    this.store[key] = value;
  }
  removeItem(key: string): void {
    delete this.store[key];
  }
  clear(): void {
    this.store = {};
  }
}

// Attach mock localStorage to global object for test isolation
(global as any).localStorage = new MockLocalStorage();

function createMockAnalysis(motifs: string[], emotions: string[], colors: string[] = ['blue']): DreamAnalysisResult {
  return {
    id: 'analysis-' + Math.random().toString(36).substring(2, 7),
    submissionId: 'sub-' + Math.random().toString(36).substring(2, 7),
    createdAt: new Date().toISOString(),
    extractedFeatures: {
      dominantMotifs: motifs.slice(0, 3),
      secondaryMotifs: motifs.slice(3),
      detectedSymbols: motifs,
      emotionalSignals: emotions,
      detectedEmotions: emotions,
      setting: ['ocean'],
      detectedLocations: ['ocean'],
      socialElements: [],
      unusualEvents: [],
      movementPatterns: [],
      sensoryImagery: [],
      detectedColors: colors,
      detectedThemes: [],
      ambiguityLevel: 'low',
      daytimeResidueProbability: 'low',
      motifsWhyNoticed: {}
    },
    culturalPerspectives: [],
    culturalPerspectivesNotFound: false,
    psychologyPerspectives: [],
    personalInterpretation: {
      title: 'Personal Reflection',
      narrativeArcs: ['One possible reading suggests exploring transition.'],
      primarySynthesis: 'One possible reading suggests exploring transition.',
      symbolicEchoes: [],
      suggestiveQuestions: [],
      possibleInterpretations: ['One possible reading suggests exploring transition.'],
      emotionalReading: 'A calm progression.',
      uncertaintyStatement: 'These reflections are suggestive.'
    },
    creativeReflection: {
      message: 'Original creative reflection inspired by your dream.',
      label: 'Original creative reflection inspired by your dream.',
      isAIGenerated: true,
      isOriginal: true
    },
    originalReflection: {
      message: 'Original thought inspired by your dream.',
      label: 'Original reflection inspired by your dream.',
      isAIGenerated: true
    },
    closingThought: {
      thought: 'Dreams open a quiet dialogue with our waking experiences.',
      label: 'Original Closing Thought'
    },
    dreamArtwork: {
      imageUrl: 'data:image/png;base64,mockArtworkData',
      promptUsed: 'A surreal painting with ' + motifs.join(', '),
      styleTheme: 'Nocturne',
      title: 'Dream Imagined',
      label: 'Your Dream — Imagined',
      subLabel: 'An artistic visualization inspired by your description.',
      visualKeywords: motifs
    }
  } as any;
}

async function runDreamJournalAndPatternTests() {
  console.log('====================================================');
  console.log('SOMNITHOS STEP 6: DREAM JOURNAL & PATTERNS TESTS');
  console.log('====================================================\n');

  const repository = new LocalStorageDreamRepository();
  StorageService.setRepository(repository);

  // ----------------------------------------------------
  // 1 & 8 & 18 & 19: Save Dream, Private Default, Artwork & Version
  // ----------------------------------------------------
  console.log('--- 1. Save Dream & Defaults ---');
  const mockAnalysis1 = createMockAnalysis(['water', 'ocean'], ['peace', 'wonder']);
  const dream1: SavedDreamRecord = {
    dreamId: 'dream-001',
    title: 'The Blue Ocean Journey',
    originalNarrative: 'I was floating smoothly over deep water under a quiet night sky.',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
    emotions: ['peace', 'wonder'],
    motifs: ['water', 'ocean'],
    setting: ['ocean'],
    analysisResult: mockAnalysis1,
    artworkReference: {
      artworkUrl: 'data:image/png;base64,mockArtworkData',
      promptUsed: 'A surreal painting with water'
    },
    privacyStatus: 'PRIVATE',
    analysisVersion: '1.0.0'
  };

  const saved1 = await repository.saveDream(dream1);
  assert.strictEqual(saved1.dreamId, 'dream-001', 'Saves dream with correct ID');
  assert.strictEqual(saved1.privacyStatus, 'PRIVATE', 'Defaults to PRIVATE');
  assert.strictEqual(saved1.analysisVersion, '1.0.0', 'Preserves analysisVersion');
  assert(saved1.artworkReference?.artworkUrl, 'Preserves artwork reference');
  console.log('✓ PASS: Dream saved with PRIVATE default and artwork metadata');

  // ----------------------------------------------------
  // 2. Retrieve Dream
  // ----------------------------------------------------
  console.log('\n--- 2. Retrieve Dream ---');
  const retrieved = await repository.getDream('dream-001');
  assert(retrieved !== null, 'Retrieves saved dream by ID');
  assert.strictEqual(retrieved?.title, 'The Blue Ocean Journey', 'Title matches');
  assert.strictEqual(retrieved?.motifs[0], 'water', 'Motifs match');
  console.log('✓ PASS: Dream retrieved successfully with complete metadata');

  // ----------------------------------------------------
  // 3 & 7: Update Dream & Duplicate Prevention
  // ----------------------------------------------------
  console.log('\n--- 3. Update Dream & Duplicate Prevention ---');
  const updatedDream1: SavedDreamRecord = {
    ...dream1,
    title: 'The Luminous Ocean Journey'
  };
  await repository.saveDream(updatedDream1);

  const listAfterUpdate = await repository.listDreams();
  assert.strictEqual(listAfterUpdate.length, 1, 'Duplicate ID updates existing record instead of appending');
  assert.strictEqual(listAfterUpdate[0].title, 'The Luminous Ocean Journey', 'Updates title');
  console.log('✓ PASS: Prevents duplicates and updates existing dream record');

  // ----------------------------------------------------
  // 4. Delete Dream
  // ----------------------------------------------------
  console.log('\n--- 4. Delete Dream ---');
  const deleteSuccess = await repository.deleteDream('dream-001');
  assert.strictEqual(deleteSuccess, true, 'deleteDream returns true on success');
  const checkDeleted = await repository.getDream('dream-001');
  assert.strictEqual(checkDeleted, null, 'Dream is removed from repository');
  console.log('✓ PASS: Deletion removes record permanently');

  // ----------------------------------------------------
  // 20. Empty Journal Behavior
  // ----------------------------------------------------
  console.log('\n--- 20. Empty Journal Behavior ---');
  const emptyList = await repository.listDreams();
  assert.strictEqual(emptyList.length, 0, 'Empty journal returns empty array without throwing');
  console.log('✓ PASS: Empty journal handled gracefully');

  // ----------------------------------------------------
  // 21. Empty Pattern Behavior
  // ----------------------------------------------------
  console.log('\n--- 21. Empty Pattern Behavior ---');
  const emptyPatterns = DreamPatternEngine.detectPatterns([]);
  assert.strictEqual(emptyPatterns.length, 0, 'No patterns returned when 0 dreams saved');
  const singleDreamPattern = DreamPatternEngine.detectPatterns([dream1]);
  assert.strictEqual(singleDreamPattern.length, 0, 'No patterns returned when only 1 dream saved (< 2 threshold)');
  console.log('✓ PASS: Empty pattern state handled properly (< 2 dreams)');

  // ----------------------------------------------------
  // Deterministic Test Dataset for Step 6 Requirements
  // Dream 1: Water + fear + calm
  // Dream 2: Water + flying + fear + calm
  // Dream 3: Water + forest + calm
  // Dream 4: Flying + curiosity
  // ----------------------------------------------------
  console.log('\n--- Deterministic Test Dataset Ingestion ---');
  const testDream1: SavedDreamRecord = {
    dreamId: 'td-1',
    title: 'Dark Waters in Sea',
    originalNarrative: 'I was submerged in dark water feeling afraid before everything became calm.',
    createdAt: '2026-08-02T12:00:00.000Z',
    updatedAt: '2026-08-02T12:00:00.000Z',
    emotions: ['fear', 'calm'],
    motifs: ['water', 'ocean'],
    setting: ['ocean'],
    analysisResult: createMockAnalysis(['water', 'ocean'], ['fear', 'calm']),
    privacyStatus: 'PRIVATE',
    analysisVersion: '1.0.0'
  };

  const testDream2: SavedDreamRecord = {
    dreamId: 'td-2',
    title: 'Flight Over Midnight Water',
    originalNarrative: 'I was flying over high water, feeling afraid then profoundly calm.',
    createdAt: '2026-08-14T12:00:00.000Z',
    updatedAt: '2026-08-14T12:00:00.000Z',
    emotions: ['fear', 'calm'],
    motifs: ['water', 'flying'],
    setting: ['ocean', 'sky'],
    analysisResult: createMockAnalysis(['water', 'flying'], ['fear', 'calm']),
    privacyStatus: 'PRIVATE',
    analysisVersion: '1.0.0'
  };

  const testDream3: SavedDreamRecord = {
    dreamId: 'td-3',
    title: 'The Forest Stream',
    originalNarrative: 'I rested by moving water inside a quiet pine forest.',
    createdAt: '2026-08-22T12:00:00.000Z',
    updatedAt: '2026-08-22T12:00:00.000Z',
    emotions: ['calm'],
    motifs: ['water', 'forest'],
    setting: ['forest'],
    analysisResult: createMockAnalysis(['water', 'forest'], ['calm']),
    privacyStatus: 'SHARED_ANONYMOUSLY',
    analysisVersion: '1.0.0'
  };

  const testDream4: SavedDreamRecord = {
    dreamId: 'td-4',
    title: 'Soaring City Lights',
    originalNarrative: 'I was flying above city towers filled with intense curiosity.',
    createdAt: '2026-08-28T12:00:00.000Z',
    updatedAt: '2026-08-28T12:00:00.000Z',
    emotions: ['curiosity'],
    motifs: ['flying', 'city'],
    setting: ['city', 'sky'],
    analysisResult: createMockAnalysis(['flying', 'city'], ['curiosity']),
    privacyStatus: 'PRIVATE',
    analysisVersion: '1.0.0'
  };

  await repository.saveDream(testDream1);
  await repository.saveDream(testDream2);
  await repository.saveDream(testDream3);
  await repository.saveDream(testDream4);

  // ----------------------------------------------------
  // 5. Search Dream
  // ----------------------------------------------------
  console.log('\n--- 5. Search Dreams ---');
  const searchWater = await repository.searchDreams('water');
  assert.strictEqual(searchWater.length, 3, 'Finds 3 dreams matching "water"');
  const searchForest = await repository.searchDreams('pine');
  assert.strictEqual(searchForest.length, 1, 'Finds narrative keyword match');
  console.log('✓ PASS: Search across title, narrative, and motifs operates accurately');

  // ----------------------------------------------------
  // 6. Filter Dreams
  // ----------------------------------------------------
  console.log('\n--- 6. Filter Dreams ---');
  const allSaved = await repository.listDreams();
  const flyingOnly = allSaved.filter(d => d.motifs.includes('flying'));
  assert.strictEqual(flyingOnly.length, 2, 'Filters 2 dreams with flying');
  const fearOnly = allSaved.filter(d => d.emotions.includes('fear'));
  assert.strictEqual(fearOnly.length, 2, 'Filters 2 dreams with fear');
  console.log('✓ PASS: Filtering by motif and emotion succeeds');

  // ----------------------------------------------------
  // 9 & 16: Anonymous Sharing Flag & Privacy Isolation
  // ----------------------------------------------------
  console.log('\n--- 9 & 16. Privacy Isolation ---');
  const sharedDreams = await repository.getSharedDreams();
  assert.strictEqual(sharedDreams.length, 1, 'Only SHARED_ANONYMOUSLY dreams returned in public query');
  assert.strictEqual(sharedDreams[0].dreamId, 'td-3', 'Identifies correct shared dream');
  console.log('✓ PASS: Private dreams are strictly excluded from shared queries');

  // ----------------------------------------------------
  // 10, 11, 12, 13, 14, 15: Pattern Engine Verification
  // ----------------------------------------------------
  console.log('\n--- 10-15. Pattern Engine Frequency & Sequences ---');
  const patterns = DreamPatternEngine.detectPatterns(allSaved);

  // 11. Motif Recurrence: Water (3) and Flying (2)
  const waterPattern = patterns.find(p => p.type === 'MOTIF' && p.label.toLowerCase() === 'water');
  assert(waterPattern !== undefined, 'Detects water pattern');
  assert.strictEqual(waterPattern?.count, 3, 'Water count = 3 dreams');
  assert.strictEqual(waterPattern?.dreamIds.length, 3, 'Matches 3 dream IDs');
  assert(waterPattern?.dreamIds.includes('td-1') && waterPattern?.dreamIds.includes('td-2') && waterPattern?.dreamIds.includes('td-3'), 'Water pattern contains exact matching IDs');

  const flyingPattern = patterns.find(p => p.type === 'MOTIF' && p.label.toLowerCase() === 'flying');
  assert(flyingPattern !== undefined, 'Detects flying pattern');
  assert.strictEqual(flyingPattern?.count, 2, 'Flying count = 2 dreams');

  // 14. No Pattern for Single Occurrence: e.g. "forest" or "city" motif appearing only once
  const cityMotif = patterns.find(p => p.type === 'MOTIF' && p.label.toLowerCase() === 'city');
  assert.strictEqual(cityMotif, undefined, 'Single occurrence motif (city) is NOT returned as recurring pattern');

  // 13. Emotional Sequence: Fear -> Calm (2 dreams)
  const seqPattern = patterns.find(p => p.type === 'EMOTIONAL_SEQUENCE');
  assert(seqPattern !== undefined, 'Detects emotional sequence pattern');
  assert.strictEqual(seqPattern?.count, 2, 'Fear → Calm occurs in 2 dreams');
  assert(seqPattern?.label.includes('Fear') && seqPattern?.label.includes('Calm'), 'Sequence label indicates transition');

  // 12. Emotion Recurrence: Calm (3), Fear (2)
  const calmPattern = patterns.find(p => p.type === 'EMOTION' && p.label.toLowerCase() === 'calm');
  assert.strictEqual(calmPattern?.count, 3, 'Calm appears in 3 dreams');

  console.log('✓ PASS: Correctly computes pattern frequency, sequences, and thresholds');

  // ----------------------------------------------------
  // 17. Non-Diagnostic Language Safeguard
  // ----------------------------------------------------
  console.log('\n--- 17. Non-Diagnostic Language Safeguard ---');
  const forbiddenPhrases = [
    'you have anxiety',
    'this proves',
    'your subconscious is telling you',
    'diagnosis',
    'you are depressed',
    'you are traumatized',
    'pathology',
    'clinical'
  ];

  patterns.forEach(p => {
    forbiddenPhrases.forEach(forbidden => {
      assert(
        !p.description.toLowerCase().includes(forbidden),
        `Pattern description must not contain diagnostic phrase: "${forbidden}"`
      );
    });
    // Check that description uses descriptive language
    assert(
      p.description.includes('appeared') || p.description.includes('experienced') || p.description.includes('transition'),
      'Pattern description uses strictly descriptive phrasing'
    );
  });
  console.log('✓ PASS: All pattern descriptions are strictly descriptive and non-diagnostic');

  console.log('\n====================================================');
  console.log('ALL 21 / 21 STEP 6 DREAM JOURNAL & PATTERN TESTS PASSED (100%)');
  console.log('====================================================\n');
}

runDreamJournalAndPatternTests().catch(err => {
  console.error('Test failed:', err);
  process.exit(1);
});
