import type { DreamSubmission, ExtractedDreamFeatures } from '../types/dream';
import type { ArtworkSpecification } from '../domain/artwork/ArtworkSpecification';
import type { ArtworkResult } from '../domain/artwork/ArtworkResult';
import { createArtworkSpecification } from '../domain/artwork/ArtworkSpecification';
import { DreamArtGenerator } from './dreamArtGenerator';

export type ImageProviderType = 'real_ai' | 'mock_ai' | 'procedural_canvas';

export interface ArtGenerationRequest {
  submission: DreamSubmission;
  features: ExtractedDreamFeatures;
  specification?: ArtworkSpecification;
  stylePresetKey?: string;
  isRegenerate?: boolean;
  variationSeed?: number;
  canvasTarget?: HTMLCanvasElement;
}

export interface ArtGenerationResponse {
  imageUrl: string;
  provider: ImageProviderType;
  promptUsed: string;
  visualElementsDetected: string[];
  generationTimeMs: number;
  isFallback: boolean;
  fallbackReason?: string;
  notes: string;
  specification?: ArtworkSpecification;
  artworkResult?: ArtworkResult;
}

export interface ImageGenerationProvider {
  id: ImageProviderType;
  name: string;
  description: string;
  generate(request: ArtGenerationRequest): Promise<ArtGenerationResponse>;
}

/**
 * Procedural HTML5 Canvas Art Provider
 * Renders faithful visual motifs entirely client-side using layered shaders and motif synthesis.
 */
export class ProceduralCanvasProvider implements ImageGenerationProvider {
  public id: ImageProviderType = 'procedural_canvas';
  public name = 'Procedural Canvas Engine';
  public description = 'Generates dream-grounded surrealist compositions directly on HTML5 Canvas using dynamic layered shaders.';

  public async generate(request: ArtGenerationRequest): Promise<ArtGenerationResponse> {
    const startTime = performance.now();
    let canvas = request.canvasTarget;
    if (!canvas) {
      canvas = document.createElement('canvas');
      canvas.width = 900;
      canvas.height = 600;
    }

    const dataUrl = DreamArtGenerator.renderDreamCanvas(
      canvas,
      request.submission,
      request.features,
      request.stylePresetKey || 'nocturne'
    );

    const endTime = performance.now();

    return {
      imageUrl: dataUrl,
      provider: 'procedural_canvas',
      promptUsed: DreamArtGenerator.synthesizeArtPrompt(request.submission, request.features),
      visualElementsDetected: DreamArtGenerator.extractVisualElements(request.submission, request.features),
      generationTimeMs: Math.round(endTime - startTime),
      isFallback: false,
      notes: 'Rendered client-side via Somnithos Procedural Scene Synthesis.'
    };
  }
}

/**
 * Backend Generative AI Artwork Provider
 * Calls server endpoint POST /api/generate-artwork with ArtworkSpecification.
 * If backend fails or is offline, falls back seamlessly to ProceduralCanvasProvider.
 */
export class GenerativeAIArtworkProvider implements ImageGenerationProvider {
  public id: ImageProviderType = 'real_ai';
  public name = 'Somnithos AI Artwork Engine (Google Imagen 3 / Gemini)';
  public description = 'Generates high-resolution museum surrealism grounded in your dream specification via secure server API.';

  private fallbackProvider = new ProceduralCanvasProvider();

  public async generate(request: ArtGenerationRequest): Promise<ArtGenerationResponse> {
    const startTime = performance.now();
    const spec = request.specification || createArtworkSpecification(
      request.submission as any,
      request.features as any,
      request.stylePresetKey || 'nocturne'
    );

    try {
      const response = await fetch('/api/generate-artwork', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          specification: spec,
          stylePresetKey: request.stylePresetKey || 'nocturne',
          isRegenerate: request.isRegenerate,
          variationSeed: request.variationSeed
        })
      });

      if (!response.ok) {
        throw new Error(`API returned HTTP ${response.status}`);
      }

      const data = await response.json();
      if (!data.success || !data.artwork) {
        throw new Error(data.error || 'Invalid API response format');
      }

      const artwork: ArtworkResult = data.artwork;
      const endTime = performance.now();

      return {
        imageUrl: artwork.imageUrl,
        provider: artwork.provider as ImageProviderType,
        promptUsed: artwork.specification.artisticStyle + ' - ' + (artwork.specification.mustInclude.join(', ') || artwork.specification.title),
        visualElementsDetected: artwork.specification.mustInclude.concat(artwork.specification.dominantSubjects),
        generationTimeMs: Math.round(endTime - startTime),
        isFallback: artwork.fallbackUsed,
        fallbackReason: artwork.fallbackReason,
        notes: artwork.fallbackUsed
          ? `Fallback: ${artwork.fallbackReason}`
          : `Generated by ${artwork.model || 'Generative AI'}. Creative visualization inspired by your description.`,
        specification: artwork.specification,
        artworkResult: artwork
      };
    } catch (err: any) {
      console.warn('Backend artwork API encountered error, switching to procedural fallback:', err);
      const fallbackResult = await this.fallbackProvider.generate(request);
      return {
        ...fallbackResult,
        provider: 'procedural_canvas',
        isFallback: true,
        fallbackReason: `Server API unavailable (${err.message || 'offline'}). Rendered via procedural engine.`,
        notes: 'Rendered using offline procedural engine fallback.'
      };
    }
  }
}

/**
 * Unified Image Generation Service Manager
 */
export class ImageGenerationService {
  private static providers: Record<ImageProviderType, ImageGenerationProvider> = {
    real_ai: new GenerativeAIArtworkProvider(),
    mock_ai: new GenerativeAIArtworkProvider(),
    procedural_canvas: new ProceduralCanvasProvider()
  };

  private static activeProviderId: ImageProviderType = 'real_ai';
  private static isGenerating: boolean = false;

  public static setProvider(providerId: ImageProviderType) {
    this.activeProviderId = providerId;
  }

  public static getActiveProvider(): ImageGenerationProvider {
    return this.providers[this.activeProviderId] || this.providers.real_ai;
  }

  public static getAllProviders(): ImageGenerationProvider[] {
    return [
      this.providers.real_ai,
      this.providers.procedural_canvas
    ];
  }

  public static isBusy(): boolean {
    return this.isGenerating;
  }

  public static async generateArtwork(request: ArtGenerationRequest): Promise<ArtGenerationResponse> {
    if (this.isGenerating) {
      // Guard against double click / duplicate requests
      throw new Error('An artwork generation request is already in progress.');
    }

    this.isGenerating = true;
    try {
      const provider = this.getActiveProvider();
      const res = await provider.generate(request);
      return res;
    } finally {
      this.isGenerating = false;
    }
  }
}
